// var left = 'I am left!';
// console.log(top.frames.length);
// console.log(top.frames[0]);
// console.log(top.frames[1]);
// console.log(top.frames['leftFrame']);
// // console.log(window.frames[1]);
// // console.log(frames[1]);
// console.log(top.frames[1]['name']);
console.log(top);
console.log(parent);
console.log(self);